- color: d73a4a
  description: Something isn't working
  name: 🐞 Bug
- color: fc3232
  description: Something to ask
  name: ❓ Question
- color: fafafa
  description: Issues that need ideas, opinions
  name: 💬 Need Opinions
- color: ff0000
  description: Spam
  name: 🚨 Spam

# README.md, YML, config, image files
- color: eb4646
  description: about README.md
  name: 📕 README.md
- color: 21e5ff
  description: about workflow files
  name: 🌊 Workflows
- color: 16fa31
  description: about image files
  name: 🖼️ Images
- color: fff821
  description: about config files
  name: 🛠️ Config

# Priority
- color: ff0000
  description: Priority Level 4
  name: ❤️ Priority#1

- color: ff8800
  description: Priority Level 3
  name: 🧡 Priority#2

- color: 00ff11
  description: Priority Level 2
  name: 💚 Priority#3

- color: 00d5ff
  description: Priority Level 1
  name: 💙 Priority#4
