# 지정된 형식 외의 issue 발행을 허용할 경우 true로 바꾸세요!
blank_issues_enabled: false

# issue 템플릿 외에 링크로 연결해주는 템플릿입니다!
# name  : 링크, 커뮤니티로 이동하는 버튼의 이름
# url   : 연결될 링크
# about : 간단한 설명
contact_links:
  - name: Google
    url: https://www.google.com/
    about: 물어보기 전에 구글링을 하셨나요?
