# from : https://github.com/marketplace/actions/label-syncer

name: Sync labels

on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
